service: serverless-test
frameworkVersion: "2"

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

plugins:
  - serverless-plugin-tracing
  - serverless-plugin-lambda-insights

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
      - sqs: arn:aws:sqs:eu-west-2:108607216059:testQueue
    tracing: true
    lambdaInsights: true
