name: Auto-deploy serverless
on: push
jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Github $GITHUB_REF"
      - run: ! echo 'Github2 ${github.ref}'
  prod-deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install serverless
        run: npm install -g serverless
      - name: Install packages
        run: npm install
      - name: Set credentials
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_PROD }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY_PROD }}
        run: |
          serverless config credentials --provider aws --key "$AWS_ACCESS_KEY" --secret "$AWS_SECRET_KEY"
      - name: Deploy
        run: serverless deploy --stage prod
  dev-deploy:
    if: ${{ github.ref == 'refs/heads/dev'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install serverless
        run: npm install -g serverless
      - name: Install packages
        run: npm install
      - name: Set credentials
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          serverless config credentials --provider aws --key "$AWS_ACCESS_KEY" --secret "$AWS_SECRET_KEY"
      - name: Deploy
        run: serverless deploy --stage dev
