name: Auto-deploy serverless
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install serverless
        run: npm install -g serverless
      - name: Install packages
        run: npm install
      - name: Set credentials
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          serverless config credentials --provider aws --key "$AWS_ACCESS_KEY" --secret "$AWS_SECRET_KEY"
      - name: Deploy
        run: serverless deploy
